# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0e59970b1697da16b435357c54b5bfb102c42925a720468ee01ab7ddabc1be2253a30f7e52875eb95c0b9604088ca44fbb85ea1286c080527cbd5387ffe54ccf

test:
  secret_key_base: 027ab8e36a314ad2d5fde5963340236d341b61f9124da50470fe251758fb5affa77e40f47949d01c7744ab5cefe142bc84fe82c646f02f82680477d4a99050bc

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
